apiVersion: 1

datasources:
  - name: MySQL
    uid: liveclass-mysql 
    type: mysql
    url: mysql:3306
    database: liveclass_logs
    user: root
    secureJsonData:
      password: root
    isDefault: true
    editable: true