{
 "title": "데이터 분석 대시보드",
 "time": { "from": "2025-01-09T06:03:31.648Z", "to": "2027-10-30T06:03:31.648Z" },
 "panels": [
  {
   "title": "강의 특성별 조회수 비율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "liveclass_logs",
     "rawSql": "SELECT\r\n    CONCAT(IF(is_main_exposed=1, '메인 노출 O', '메인 노출 X'), ' / ', IF(course_fee > 0, '유료', '무료')) AS metric,\r\n    COUNT(*) AS value\r\nFROM traffic_logs\r\nGROUP BY course_id, is_main_exposed, course_fee\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "쿠폰 사용 여부에 따른 결제 퍼널 비율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "arcmin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "liveclass_logs",
     "rawSql": "SELECT \r\n    status AS metric, \r\n    COUNT(*) AS value\r\nFROM (\r\n    SELECT \r\n        session_id,\r\n        CASE  \r\n            WHEN MAX(IF(event_type = 'PAYMENT_COMPLETED', 1, 0)) = 0 THEN '결제 미완료 (이탈)'\r\n            WHEN MAX(IF(event_type = 'PAYMENT_COMPLETED' AND coupon_id IS NOT NULL, 1, 0)) = 1 THEN '쿠폰 사용 결제'\r\n            ELSE '쿠폰 미사용 결제'\r\n        END AS status\r\n    FROM payment_logs\r\n    WHERE session_id IN (\r\n        SELECT session_id \r\n        FROM payment_logs \r\n        WHERE event_type = 'ADD_TO_CART'\r\n    )\r\n    GROUP BY session_id\r\n) AS funnel\r\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "결제 실패시 에러 코드별 비율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "liveclass_logs",
     "rawSql": "SELECT error_code AS metric, COUNT(*) AS value\r\nFROM payment_logs\r\nWHERE event_type = 'PAYMENT_FAILED'\r\nGROUP BY error_code\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "결제 수단별 에러 비율",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "liveclass_logs",
     "rawSql": "SELECT\r\n    payment_method,\r\n    completed,\r\n    failed\r\nFROM (\r\n    SELECT\r\n        payment_method,\r\n        SUM(CASE WHEN event_type = 'PAYMENT_COMPLETED' THEN 1 ELSE 0 END) AS completed,\r\n        SUM(CASE WHEN event_type = 'PAYMENT_FAILED' THEN 1 ELSE 0 END) AS failed,\r\n        COUNT(*) AS total_cnt\r\n    FROM payment_logs\r\n    WHERE event_type IN ('PAYMENT_COMPLETED', 'PAYMENT_FAILED')\r\n    GROUP BY payment_method\r\n) t\r\nORDER BY total_cnt ASC;"
    }
   ]
  },
  {
   "title": "환불 사유별 비율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 9 },
   "targets": [
    {
     "dataset": "liveclass_logs",
     "rawSql": "SELECT refund_reason AS metric, COUNT(*) AS value\r\nFROM refund_logs\r\nGROUP BY refund_reason;"
    }
   ]
  }
 ]
}